- id: 'ricecooker_notification'
  alias: Ricecooker Notification
  description: ''
  trigger:
  - platform: time
    at: sensor.ricecooker_finish_time
  condition: []
  action:
  - service: notify.telegram_daniel
    data:
      message: "\U0001F35A Reiskocher fertig! \U0001F35A"
  mode: single