mqtt:
  switch:
    - name: "Rice Cooker Sound Detector"
      command_topic: "sounddetector/cmds"
      state_topic: "sounddetector/state"
      payload_on: "systemctl start sounddetector"
      payload_off: "systemctl stop sounddetector"
      state_off: "offline"
      state_on: "online"
      icon: mdi:rice
  sensor:
    - name: "Ricecooker Finish Time"
      state_topic: "sounddetector/ricecooker_finish_time"
      value_template: "{{ value_json.datetime }}"


