switch:
  - platform: mqtt
    name: "Sound Detector"
    command_topic: "sounddetector/cmds"
    state_topic: "sounddetector/state"
    payload_on: "systemctl start sounddetector"
    payload_off: "systemctl stop sounddetector"
    state_off: "offline"
    state_on: "online"
    icon: mdi:music-note

sensor:
  - platform: mqtt
    name: "Doorbell Detector"
    state_topic: "sounddetector/doorbell"
    value_template: "{{ value_json.datetime }}"


